// vue-test/src/App.vue
<template>
    <div>
        <h1>Vue Test App</h1>
        <div class="row">
            <master />
            <detail />
        </div>
    </div>
</template>

<script>
import qs from 'qs'
import Master from './components/Master'
import Detail from './components/Detail'

export default {
    name: 'app',
    components: {
        Master, Detail
    },
    beforeCreate: function () {
        const {access_token} = qs.parse(
            window.location.hash.replace(/^#/, ''))
        if (access_token) {
            this.$store.dispatch('saveAccessToken', access_token)
        }
    }
}
</script>

// angular2-test/app/app.component.ts
import { Component }   from '@angular/core';
import { HashLocationStrategy }   from '@angular/common';
import {parse} from 'qs';
import {AuthService} from './auth.service';

@Component({
    selector: 'my-app',
    template: `
        <h1>Angular App Test</h1>
        <div class="row">
            <div class="column"><master></master></div>
            <div class="column"><detail></detail></div>
       </div>
    `
})
export class AppComponent {
    constructor(
        private hash: HashLocationStrategy,
        private auth: AuthService
    ) {
        const {access_token} = parse(hash.path())

        if(access_token) {
            auth.saveAccessToken(access_token);
            location.href = '/'
        }
    }
}
