// vue-test/src/components/Detail.vue
<template>
    <div class="column">
        <h3>Detail</h3>
        <a v-if="access_token" class="button" v-on:click="logout">Logout</a>
        <a v-if="!access_token" class="button" v-on:click="login">Login</a>
    </div>
</template>

<script>
import { mapGetters } from 'vuex'
import {stringify} from 'qs'

export default {
    name: 'detail',
    computed: mapGetters({
        access_token: 'getAccessToken'
    }),
    methods: {
        login: function () {
            const para = {
                response_type: 'token',
                client_id: 'x2adb4mzqfp868e',
                redirect_uri: 'http://localhost:8080'
            }
            window.location.href =
                `https://www.dropbox.com/1/oauth2/authorize?${stringify(para)}`
        },
        logout: function () {
            this.$store.dispatch('saveAccessToken', '')
        }
    }
}
</script>

// angular2-test/app/detail.component.ts
import {stringify} from 'qs';
import {Component}   from '@angular/core';
import { DefaultUrlSerializer, UrlSegment, UrlTree, UrlSerializer } from '@angular/router';
import {AuthService} from './auth.service';

@Component({
    selector: 'detail',
    template: `
        <h3>Detail</h3>
        <a class="button" (click)="onLogout()" *ngIf="access_token">Logout</a>
        <a class="button" (click)="onLogin()" *ngIf="!access_token">Login</a>
    `,
})
export class DetailComponent {
    private access_token: string
    private authService: AuthService

    constructor(authService: AuthService) {
        this.authService = authService
        this.access_token = authService.getAccessToken()
    }

    onLogin() {
        const para = {
            response_type: 'token',
            client_id: 'x2adb4mzqfp868e',
            redirect_uri: 'http://localhost:3000'
        }
        window.location.href =
            `https://www.dropbox.com/1/oauth2/authorize?${stringify(para)}`
    }

    onLogout() {
        this.authService.saveAccessToken('')
        location.reload()
    }
}
