// react-test/src/detail.jsx
import React, {PropTypes} from 'react';
import {stringify} from 'qs';
import {connect} from 'react-redux';
import {saveAccessToken} from './store/action.js';

class Detail extends React.Component {
    static propTypes = {
        dispatch: PropTypes.func,
        auth: PropTypes.object
    };
    _login() {
        const para = {
            response_type: 'token',
            client_id: 'x2adb4mzqfp868e',
            redirect_uri: 'http://localhost:8080'
        };
        window.location.href =
            `https://www.dropbox.com/1/oauth2/authorize?${stringify(para)}`;
    }
    _logout() {
        this.props.dispatch(saveAccessToken(''));
    }
    render() {
        const {access_token} = this.props.auth;

        return (
            <div className="column">
                <h3>Detail</h3>
                {access_token ?
                    (<a className="button" onClick={this._logout.bind(this)}>Logout</a> ) :
                    (<a className="button" onClick={this._login.bind(this)}>Login</a>)
                 }
            </div>
        );
    }
}

export default connect(state => state)(Detail);

// vue-test/src/components/Detail.vue
<template>
    <div class="column">
        <h3>Detail</h3>
        <a v-if="access_token" class="button" v-on:click="logout">Logout</a>
        <a v-if="!access_token" class="button" v-on:click="login">Login</a>
    </div>
</template>

<script>
import { mapGetters } from 'vuex'
import {stringify} from 'qs'

export default {
    name: 'detail',
    computed: mapGetters({
        access_token: 'getAccessToken'
    }),
    methods: {
        login: function () {
            const para = {
                response_type: 'token',
                client_id: 'x2adb4mzqfp868e',
                redirect_uri: 'http://localhost:8080'
            }
            window.location.href =
                `https://www.dropbox.com/1/oauth2/authorize?${stringify(para)}`
        },
        logout: function () {
            this.$store.dispatch('saveAccessToken', '')
        }
    }
}
</script>
